---
configure_dotfiles: false
configure_terminal: true
configure_osx: true
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - App Store
  - Contacts
  - Maps
  - FaceTime
  - Phone
  - Freeform
  - Music
  - Games
  - iPhone Mirroring
  - Reminders
configure_sudoers: false
sudoers_custom_config: ""
homebrew_installed_packages:
  - gh
  - iperf
  - nmap
  - ssh-copy-id
  - wget
  - zsh-history-substring-search
  - mas
  - neofetch
  - mackup
  - kubectl
  - helm
  - terraform
  - uv
  - oh-my-posh
  - antidote
  - zsh-autosuggestions
  - zsh-syntax-highlighting
homebrew_taps:
  - buo/cask-upgrade
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - zen-browser
  - brave-browser
  - telegram
  - whatsapp
  - visual-studio-code
  - zed
  - lm-studio
  - ghostty
  - dbeaver-community
  - tailscale
  - iina
  - keka
  - 1password
  - ente-auth
  - shottr
  - zoom
  - proton-mail-bridge
  - font-intone-mono-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-fira-mono-nerd-font
  - font-Mononoki-nerd-font
  - steam
  - crossover
mas_installed_apps:
  - id: 1614007873
    name: Tapo
  - id: 361309726
    name: Pages
  - id: 361304891
    name: Numbers
  - id: 1136220934
    name: Infuse
  - id: 1569813296
    name: 1Password for Safari
  - id: 1136220934
    name: Infuse
composer_packages: []
gem_packages: []
npm_packages: []
pip_packages: []
configure_sublime: false
sublime_base_path: ~/Library/Application Support/Sublime Text
sublime_config_path: Packages/User
sublime_package_control:
  - DocBlockr
  - Dockerfile Syntax Highlighting
  - FileDiffs
  - GitHub Flavored Markdown Preview
  - Jinja2
  - Package Control
  - Pretty JSON
  - SublimeLinter
  - SublimeLinter-contrib-yamllint
  - Theme - Cobalt2
  - TrailingSpaces
  - WordingStatus
post_provision_tasks: []
