---
configure_dotfiles: false
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
  - Contacts
  - Maps
  - FaceTime
  - Phone
  - Freeform
  - Music
  - Games
  - "iPhone Mirroring"
  - Reminders

#dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/flowy0/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_repo_version: master # Replace with your default branch
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - gh
  - iperf
  - nmap
  - ssh-copy-id
  - wget
  - zsh-history-substring-search
  - mas
  - neofetch
  - mackup
  - kubectl
  - helm
  - terraform
  - uv
  - oh-my-posh
  - antidote
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_taps:
  - buo/cask-upgrade

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - zen-browser
  - brave-browser
  - telegram
  - whatsapp
  - visual-studio-code
  - zed
  - lm-studio
  - ghostty
  - dbeaver-community
  - tailscale
  - iina
  - keka
  - 1password
  - ente-auth
  - shottr
  - zoom
  - proton-mail-bridge
  - font-intone-mono-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-fira-mono-nerd-font
  - font-Mononoki-nerd-font
  - steam
  - crossover

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1614007873, name: "Tapo" }
  - { id: 361309726, name: "Pages" }
  - { id: 361304891, name: "Numbers" }
  - { id: 1136220934, name: "Infuse" }
  - { id: 1569813296, name: "1Password for Safari" }
  - { id: 1136220934, name: "Infuse" }

#mas_email: ""
#mas_password: ""

#osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
